### ISSUE TITLE
When all default tabs are disabled show custom tab content

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/affiliatewp-affiliate-area-tabs#14] opened 2016-05-18 20:08 UTC
The affiliate area renders the last default tab URL (.../affiliate-area/?tab=settings) when default tabs are enabled, thus showing a blank affiliate area with a linked tab:
![screen shot 2016-05-18 at 3 05 26 pm](https://cloud.githubusercontent.com/assets/4752949/15373197/fbaa5d02-1d09-11e6-9302-7b969244314f.png)

An affiliate must click the custom tab to show the contents therein.

**Comment by sumobi** [comment] 2016-05-18 20:24
@michaelbeil Can you outline some steps to replicate, I'm not following. Is this on 1.8.1 and latest master of Affiliate Area Tabs?

**Comment by michaelbeil** [comment] 2016-05-18 20:39
AffiliateWP 1.8.1 and latest master of Affiliate Area Tabs.

Steps to replicate:
1. Disable all default tabs
2. Add a new custom tab
3. Go to the affiliate area and you would notice the current tab URL is still set to a default tab

**Comment by sumobi** [comment] 2016-05-18 20:57
Ahh I see now, the ?settings bit threw me off. That will only show if you were on the settings tab initially, removed it, and then refreshed the page, which is understandable since it doesn't exist.

So the issue is if you go to the Affiliate Area with all default tabs removed, it's not loading the custom tab's content correctly.

**Comment by michaelbeil** [comment] 2016-05-18 21:32
Ah yes, sorry, that happened on the first couple phases as I forgot to refresh the page. 

Correct, the custom tab content is not loading correctly with all default tabs removed.

**Comment by sumobi** [comment] 2016-05-18 21:52
I'm going to tackle this

**Comment by sumobi** [comment] 2016-05-18 23:02
@michaelbeil Could you pull down latest master and try and break it now?

**Comment by michaelbeil** [comment] 2016-05-18 23:06
It is so broken it works!

**Comment by sumobi** [comment] 2016-05-18 23:24
👍  Fixed via https://github.com/AffiliateWP/affiliatewp-affiliate-area-tabs/commit/db9ece0631a5b75f1c828690434abf3cfeae869f

**Comment by sumobi** [comment] 2016-05-19 00:41
Reopening, needs some more work. If the tab title doesn't match the page title it won't load the content.

**Closed** 2016-05-19 01:24 UTC
Labels: bug

**Comment by michaelbeil** [comment] 2016-05-19 18:58
I was going to add that issue here, but glad it was all resolved.
